#######################################
# Ignite Installlation Playbook v1.0  #
# Developed By: Sandip Bhowmik        #
# Date:                               #
#######################################
- name: Install Ignite Cluster to 2.8.0
  hosts: ignite-nodes
  become: true
  any_errors_fatal: true
  tasks:
    - name: Create Ignite user
      user:
        name: ignite
        password: "{{ 'passW0rd' | password_hash('sha512') }}"
        shell: /sbin/nologin
        update_password: on_create
    
    - name: Creates directory
      file:
        path: /data
        state: directory
        owner: ignite
        group: ignite
        recurse: yes

    - name: Unzip the Ignite 2.7.6 Binary
      unarchive:
        src: /opt/apache-ignite-2.8.0-bin.zip
        dest: /usr/
        owner: ignite
        group: ignite

    - name: Change the ownership of unzipped binary 2.8.0
      file:
        path: /usr/apache-ignite-2.7.6-bin
        state: directory
        recurse: yes
        owner: ignite
        group: ignite

    - name: Log4j Lib Copy for Ignite 2.8.0
      copy:
        src: /usr/apache-ignite-2.8.0-bin/libs/optional/ignite-log4j
        dest: /usr/apache-ignite-2.8.0-bin/libs/
        owner: ignite
        group: ignite
        remote_src: yes

    - name: Copy systemd service file to server
      copy:
        src: /root/ignite.service
        dest: /lib/systemd/system

    - name: Copy Ignite Startup Script to all nodes
      copy:
        src: /root/startIgnite.sh
        dest: /home/ignite
        owner: ignite
        group: ignite
        mode: 0755

    - name: Copy the Config file
      copy:
        src: /root/ignitedev-config.xml
        dest: /usr/apache-ignite-2.7.6-bin/config
        owner: ignite
        group: ignite

    - name: Copy the Log4j Config file
      copy:
        src: /root/ignitedev-log4j.xml
        dest: /usr/apache-ignite-2.8.0-bin/config
        owner: ignite
        group: ignite

    - name: Get all JKS files
      shell: find /root/ -type f -name \*.jks
      register: nginx_managed_virtual_hosts

    - name: Copy all JKS files to config dir
      copy:
        src: "{{ item }}"
        dest: /usr/apache-ignite-2.8.0-bin/config
        owner: ignite
        group: ignite
      with_items: "{{ nginx_managed_virtual_hosts.stdout_lines }}"
    
    - name: Ensure Current Ignite is running
      systemd: 
        state: started
        name: ignite

    - name: Checking the Status of Ignite Service
      shell: systemctl status ignite
      register: ignitestatus

    - name: Checking the Status of Ignite Service
      debug: var=ignitestatus.stdout_lines
